Move matching functionality into a separate method
tlovett1/safe-redirect-manager pull request #176
Opened 2019-07-15 20:27 UTC by ostowe

### Description of the Change
I've moved all functionality related to matching a request URL with a redirect into its own method in the `SRM_Redirect` singleton. This method will set new `$redirect_from`, `$redirect_to`, and `$status_code` class properties, allowing developers to access those values without actually following the redirect.

### Alternate Designs
None considered.

### Benefits
This PR does not change any of the underlying functionality of safe redirect manager, but it does allow more flexibility when integrating with SRM. In my case, I am building a headless WordPress site and need the ability to find a redirect match without actually following the redirect, then pass the resulting information about the match back through the WP API.

### Possible Drawbacks
This PR reorganizes code fairly substantially, and may cause merge conflicts with existing PRs if merged.

### Verification Process
* Ran all existing tests to make sure they passed.
* Hand-tested a variety of redirects.

### Checklist:
- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

2019-10-11 18:25 UTC, adamsilverstein commented on inc/classes/class-srm-redirect.php
> +			do_action( 'srm_do_redirect', $redirect_match['requested_path'], $redirect_match['redirect_to'], $redirect_match['status_code'] );
after this change the action only fires if redirect_to is set, before this change it looks like it fired regardless - any reason to change that @ostowe?

2019-10-11 18:26 UTC, adamsilverstein commented on inc/classes/class-srm-redirect.php
> +		if ( ! empty( $redirect_match['redirect_to'] ) ) {
maybe this should be checking redirect_from, as originally?

2019-10-11 18:27 UTC, adamsilverstein commented on inc/classes/class-srm-redirect.php
> +	 * Check current url against redirects
```suggestion
	 * Check current url against redirects.
```

2019-10-11 18:28 UTC, adamsilverstein requested changes
@ostowe This is looking good! I left a few small change requests. This could use more testing and ideally unit tests to back up the change.

2019-10-12 18:21 UTC, ostowe commented
Thanks for the feedback, @adamsilverstein! I'll review and address as soon as I can.

2019-11-25 14:31 UTC, nicholasio commented
Just created another PR to address the same thing: https://github.com/10up/safe-redirect-manager/pull/198

2020-11-09 19:42 UTC, jeffpaul commented
Closing in favor of the merged #198.

2020-11-09 19:42 UTC, closed without merging