Fix/24 caching strategy not effective with 1000 redirects
tlovett1/safe-redirect-manager pull request #326
Opened 2023-06-24 11:07 UTC by sksaju

### Description of the Change

To reduce the number of queries in half, we're removing `get_post_status()` from the transient. Its value is always 'publish' and it's not used anywhere, except for being printed in the cli_list

Closes #https://github.com/10up/safe-redirect-manager/issues/24

### How to test the Change

I've inserted 10,001 redirects data using CLI and tested performance using Query Monitor plugin

**Wirh `get_post_status()`:**

| Page generation | Peak memory usage | Total time of queries | Number of queries |
| ---------------- | -------------------- | --------------------- | ------------------ |
| 0.7642s - 2.5% of 30s limit | 29.9 MB - 23.4% of 128 MB server limitt | 0.1816s | 2056 |

**Without `get_post_status()`:**

| Page generation | Peak memory usage | Total time of queries | Number of queries |
| ---------------- | -------------------- | --------------------- | ------------------ |
| 0.5878s - 2.0% of 30s limit | 18.8 MB - 14.7% of 128 MB server limit | 0.0917s | 1056 |
- 

### Changelog Entry

> Added - New feature
> Changed - Existing functionality
> Deprecated - Soon-to-be removed feature
> Removed - Feature
> Fixed - Bug fix
> Security - Vulnerability

### Credits

Props @username, @username2, ...

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2023-06-30 16:50 UTC, ravinderk reviewed
@dkotter I think removing `post_status` from data will remove a few unnecessary queries. Including `post_status` make sense if were are doing a query with `post_status=> any`, which we are doing only from CLI.

I suggest keeping `post_status` in the result for queries with `post_status=> any` or only for CLI commands.

This pull request does not resolve the issue entirely but is an excellent first foot for performance improvement.

I am looking forward to your thought.

cc: @jeffpaul

2023-06-30 20:24 UTC, dkotter commented
> I suggest keeping post_status in the result for queries with post_status=> any or only for CLI commands.

Okay, that was the biggest thing to make sure of here, that there was no downside to removing this check. Sounds like we may need to keep this at least in `WP-CLI` contexts or maybe just anytime the query has `post_status => 'any'`

> This pull request does not resolve the issue entirely but is an excellent first foot for performance improvement.

Yes, there's other things we could look at doing but seemed like this was by far the easiest thing to work on initially. We may come back to some of the other things that were discussed on #24

2023-07-03 16:36 UTC, ravinderk requested changes
@sksaju As you can see, I discussed with @dkotter (https://github.com/10up/safe-redirect-manager/pull/326#issuecomment-1615160076); we decided to include `post_status` in the result if `post_status` can have more that one value which is possible if querying with `post_status => any` or `post_status => { array of post status }`.

 Can you make this change to the pull request? Let me know if you have any questions.

2023-07-05 07:12 UTC, sksaju commented
> @sksaju As you can see, I discussed with @dkotter ([#326 (comment)](https://github.com/10up/safe-redirect-manager/pull/326#issuecomment-1615160076)); we decided to include `post_status` in the result if `post_status` can have more that one value which is possible if querying with `post_status => any` or `post_status => { array of post status }`.
> 
> Can you make this change to the pull request? Let me know if you have any questions.

Yeah, I've updated the PR. Thanks

2023-07-05 12:13 UTC, ravinderk requested changes
@sksaju Let me know if the requirement needs to be clarified (https://github.com/10up/safe-redirect-manager/pull/326#pullrequestreview-1511508897).

You can follow this checklist:
- [x]  include `post_status` in the result of each redirect only if the `post_status` value varies in the `srm_get_redirects` function.

```php
// Check whether include post_status in result
$include_post_status_in_result = is_array( $query_args['post_status'] )
    || 'any' === $query_args['post_status'];
				
// Include post_status conditionally in the loop.
if( $include_post_status_in_result ) {
    $redirect_data['post_status'] = get_post_status( $redirect_id );
}
```
- [ ] Could you ensure the above code does not create regression?
- [ ] Add `Testing Instructions` to pull request description.

2023-07-19 17:32 UTC, ravinderk commented
@sksaju, do you have any questions about my recent [comment](https://github.com/10up/safe-redirect-manager/pull/326#pullrequestreview-1514372652)?

2023-07-19 19:15 UTC, sksaju commented
> @sksaju, do you have any questions about my recent [comment](https://github.com/10up/safe-redirect-manager/pull/326#pullrequestreview-1514372652)?

Hi @ravinderk, Thank you for your feedback. I've implemented the check you mentioned and tested it locally. Please review the latest commit and let me know if there's anything else I can do. Thanks.

2023-07-20 13:54 UTC, ravinderk approved these changes

2023-07-20 16:59 UTC, ravinderk commented
@dkotter We can merge this pull request.

2023-07-24 14:54 UTC, merged